apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
        - name: users
          image: lapeko/users:latest
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_URL
              value: http://auth-service.default:3000
            - name: MONGODB_URI
              value: mongodb+srv://developer:t3S5MPctj8Ps0jPB@cluster0.qzhzb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-app
spec:
  type: LoadBalancer
  selector:
    app: users-app
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000