services:
  auth:
    build: ./auth
    environment:
      PORT: 80

  tasks:
    build: ./tasks
    environment:
      PORT: 8000
      FS_DB_PATH: ./db/db.txt
      AUTH_PATH: http://auth:80
    ports:
      - "8000:8000"

  users:
    build: ./users
    environment:
      PORT: 8080
      AUTH_URL: http://auth:80
    ports:
      - "8080:8080"