apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  type: LoadBalancer
  selector:
    app: go-server-pod
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server-deployment
spec:
  selector:
    matchLabels:
      app: go-server-pod
  template:
    metadata:
      labels:
        app: go-server-pod
    spec:
      containers:
        - name: go-server
          image: lapeko/go-server:0.0.3
          ports:
            - containerPort: 3000
