apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  type: LoadBalancer
  selector:
    app: go-server-pod
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server-pod
  template:
    metadata:
      labels:
        app: go-server-pod
    spec:
      containers:
        - name: go-server
          image: lapeko/go-server:0.0.4
          env:
            - name: DATA_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: data_folder
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/permanent-data
              name: go-server-storage
      volumes:
        - name: go-server-storage
          persistentVolumeClaim:
            claimName: text-data-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: text-data-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-data-claim
spec:
  storageClassName: ""
  volumeName: text-data-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-map
data:
  data_folder: "permanent-data"