FROM golang:alpine

RUN go install github.com/cespare/reflex@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

ARG DEFAULT_PORT=3000
ENV PORT $DEFAULT_PORT

EXPOSE $PORT

CMD ["reflex", "-r", "\\.go$", "--decoration=plain", "--start-service", "go", "run", "./cmd/api/main.go"]
