services:
  auth:
    container_name: auth-go-api
    build: ./auth
    ports:
      - "8000:3000"
    environment:
      TOKEN_KEY: "SECURE_TOKEN"

  users:
    container_name: users-go-api
    build: ./users
    ports:
      - "8030:3000"
    environment:
      AUTH_URL: "http://auth:3000"
      MONGODB_URI: "mongodb+srv://developer:t3S5MPctj8Ps0jPB@cluster0.qzhzb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"