services:
  auth:
    container_name: auth-go-api
    build: ./auth
    ports:
      - "8000:3000"
    environment:
      TOKEN_KEY: "SECURE_TOKEN"

  users:
    container_name: users-go-api
    build: ./users
    depends_on:
      - mongo
    ports:
      - "8030:3000"
    environment:
      AUTH_URL: "http://auth:3000"
      MONGODB_URI: "mongodb://root:1234@mongo:27017"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - go_api_mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  go_api_mongo: