apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    group: example
spec:
  replicas: 1
  selector:
#    matchLabels:
#      app: second-go-app
#      tier: backend
    matchExpressions:
      - key: app
        operator: In
        values:
          - second-go-app
          - first-go-app
  template:
    metadata:
      labels:
        app: second-go-app
        tier: backend
    spec:
      containers:
        - name: second-go-node
          image: lapeko/go-server:0.0.2
