apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-go-app
      tier: backend
  template:
    metadata:
      labels:
        app: second-go-app
        tier: backend
    spec:
      containers:
        - name: second-go-node
          image: lapeko/go-server:0.0.2
