apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth
          image: lapeko/auth
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "80"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-app
spec:
  type: ClusterIP
  selector:
    app: auth-app
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
