apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deploy
spec:
  selector:
    matchLabels:
      app: tasks-app
  template:
    metadata:
      labels:
        app: tasks-app
    spec:
      containers:
        - name: tasks
          image: lapeko/tasks
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8000"
            - name: AUTH_PATH
              value: "http://auth-service.default"
            - name: FS_DB_PATH
              value: "./db/db.txt"

---
apiVersion: v1
kind: Service
metadata:
  name: tasks-service
  labels:
    app: tasks-app
spec:
  type: ClusterIP
  selector:
    app: tasks-app
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 8000
