apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deploy
spec:
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
      - name: users
        image: lapeko/users
        imagePullPolicy: IfNotPresent
        env:
          - name: AUTH_URL
            value: "http://auth-service.default"
          - name: PORT
            value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-app
spec:
  type: LoadBalancer
  selector:
    app: users-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
